# Jupyter에서 help 사용팁

<div class="alert alert-warning">
    NOTE: This corresponds to <a href="https://www.youtube.com/watch?v=ZYX0FaqUeN4&t=23s&list=PLlMkM4tgfjnLSOjrEJN31gZATbcj_MpUm&index=25">Lab 8 of Deep Learning Zero to All Season 1 for TensorFlow</a>.
</div>

In [1]:
import numpy as np
import torch

In [2]:
# Tab눌러서 자동 완성
# torch.s

In [12]:
# What about all `*Tensor`s?
torch.*Tensor?

In [13]:
# Annotate your functions / classes!
torch.add?

## 1D Array with NumPy

In [14]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [6]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  1
Shape of t:  (7,)


In [18]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


## 2D Array with NumPy

In [26]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [27]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


In [10]:
print(t[:,2])
print(type(t[:,2]))
print(np.shape(t[:,2]))

[ 3.  6.  9. 12.]
<class 'numpy.ndarray'>
(4,)


## PyTorch is like NumPy (but better)

### 1D Array with PyTorch

In [30]:
t = torch.Tensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [31]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [37]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [1., 11.,12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [ 1., 11., 12.]])


In [38]:
print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [ 1., 11.]])


## Shape, Rank, Axis

In [61]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]]])

In [62]:
print(t)

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]])


In [63]:
print(t.dim())  # rank  = 4
print(t.size()) # shape = (1, 2, 3, 4)
print(t.shape)

4
torch.Size([1, 2, 3, 4])
torch.Size([1, 2, 3, 4])


## Squeeze, unsqueeze, cat

In [53]:
t = t.squeeze()

In [54]:
print(t.dim())  # rank  = 4
print(t.shape)

3
torch.Size([2, 3, 4])


In [44]:
print(t)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])


In [45]:
t = t.unsqueeze(-1)

In [46]:
print(t.dim())  # rank  = 4
print(t.shape)

4
torch.Size([2, 3, 4, 1])


In [51]:
t = t.unsqueeze(-1)
print(t)

tensor([[[[[ 1.],
           [ 2.],
           [ 3.],
           [ 4.]],

          [[ 5.],
           [ 6.],
           [ 7.],
           [ 8.]],

          [[ 9.],
           [10.],
           [11.],
           [12.]]],


         [[[13.],
           [14.],
           [15.],
           [16.]],

          [[17.],
           [18.],
           [19.],
           [20.]],

          [[21.],
           [22.],
           [23.],
           [24.]]]]])


In [49]:
t = t.squeeze().unsqueeze(0)
print(t)

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]])


In [60]:
print(t.dim())  # rank  = 4
print(t.shape)

2
torch.Size([2, 2])


In [64]:
print(torch.cat([t, t], dim=0))
print(torch.cat([t, t], dim=0).shape)

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]],


        [[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]])
torch.Size([2, 2, 3, 4])


## broadcast

In [57]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

# Mat + scalar
m1 = torch.FloatTensor([[1, 2], [1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 * m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[3., 6.],
        [3., 6.]])


## mean, sum

In [59]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.shape)
print(t)

print("=======mean======")
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

print("=======sum======")
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

torch.Size([2, 2])
tensor([[1., 2.],
        [3., 4.]])
=======mean======
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])
=======sum======
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Named tensors
### color to gray

In [26]:
img_t = torch.randn(3, 5, 5)
batch_t = torch.randn(2, 3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722]) # RGB weights

# naive color to gray
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
print(img_gray_naive.shape, batch_gray_naive.shape)

torch.Size([5, 5]) torch.Size([2, 5, 5])


In [27]:
#weighted color to gray
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1) 
img_weights = (img_t * unsqueezed_weights) 
batch_weights = (batch_t * unsqueezed_weights) 
img_gray_weighted = img_weights.sum(-3) 
batch_gray_weighted = batch_weights.sum(-3)
print(img_gray_weighted.shape, batch_gray_weighted.shape)

torch.Size([5, 5]) torch.Size([2, 5, 5])


### Max and Argmax

In [28]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max()) # Returns one value: max
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


### View

In [29]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [30]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [31]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### In-place Operation

In [32]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)
print(x.zero_())
print(x)
print(x.add_(99))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[99., 99.],
        [99., 99.]])
tensor([[99., 99.],
        [99., 99.]])
